Repository VictorKabata/DarajaMultiplatform, pull requests merged in 2023-01, with the labels that each got.

#47 fix a typo on `README.md`
  README.md
Labels: Documentation

#50 Fix android publish workflow
  .github/workflows/publish_android.yml
Labels: CI/CD

#54 Formatting time by adding zeros
  daraja/src/commonMain/kotlin/com/vickbt/darajakmp/utils/Utils.kt
  daraja/src/commonTest/kotlin/com/vickbt/darajakmp/utils/UtilsTest.kt
Labels: code improvement

#55 Update phone number formatter and tests
  daraja/src/commonMain/kotlin/com/vickbt/darajakmp/utils/Utils.kt
  daraja/src/commonTest/kotlin/com/vickbt/darajakmp/utils/UtilsTest.kt
Labels: Test
